version: '3.1'
services:
  app:
    container_name: vending-machine-app-postgresql
    image: vending-machine-app-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vendingmachine