FROM openjdk:11
VOLUME /tmp
ARG REGION_ARG=ap-south-1
ARG ACCESS_ARG
ARG SECRET_ARG
ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$ACCESS_ARG
ENV AWS_SECRET_KEY=$SECRET_ARG
ARG JAR_FILE=target/*.jar
ENTRYPOINT ["java", "-jar", "vending_machine-0.0.1-SNAPSHOT.jar"]
